### ISSUE TITLE
`npm install` fastboot dependencies removes node_modules if using `yarn.lock`

### ISSUE THREAD

**Issue by bantic** [heroku/heroku-buildpack-ember-cli-deploy#12]
I'm using the meta [emberjs buildpack](https://github.com/heroku/heroku-buildpack-emberjs) that relies on this one, and running into an issue with node_modules not being present at Heroku.

In addition to the devDependencies necessary for building my ember app, I have one production dependency (rollbar, the error reporter) that I'm using when running the fastboot app at Heroku.
My Procfile runs a node script to launch the app:
```
# Procfile
web: node serve.js
```

```
// serve.js
const FastBootAppServer = require('fastboot-app-server');
const Rollbar = require('rollbar');

let rollbar;

if (process.env.ROLLBAR_ACCESS_TOKEN) {
  rollbar = new Rollbar(process.env.ROLLBAR_ACCESS_TOKEN);
}

let server = new FastBootAppServer({
  distPath: 'dist',
  gzip: true, // Optional - Enables gzip compression.
  host: '0.0.0.0', // Optional - Sets the host the server listens on.
  afterMiddleware(app) {
    if (rollbar) {
      app.use(rollbar.errorHandler());
    }
  }
});

server.start();
```

When I attempt to push this to Heroku the build succeeds but running the app fails because it cannot find the module "rollbar".

I'm also using yarn (and a committed `yarn.lock`) file with this project, which turns out to be the source of my issue.

I believe this is the sequence of events that happens when pushing to heroku:
 -   heroku-buildpack-emberjs [sets NPM_CONFIG_PRODUCTION to `false`](https://github.com/heroku/heroku-buildpack-emberjs/blob/65183ada0c0ae22285e2b3027f34b129c34416e0/buildpack/mrblib/buildpack/commands/compile.rb#L28)
 - heroku-buildpack-emberjs runs the heroku-buildpack-nodejs buildpack, which, due to presence of `yarn.lock` [installs node modules using yarn](https://github.com/heroku/heroku-buildpack-nodejs/blob/c02a4b9726b70fc8cfa79aa972d019db37c4076d/lib/dependencies.sh#L73-L83) (I'm not sure if the `NPM_CONFIG_PRODUCTION:false` is still set here and if it is required for the `yarn install` to work — either way, the yarn install does work and the devDependencies are installed at this point)
 - heroku-buildpack-emberjs runs this buildpack, and it uses npm to [install again (and conditionally also run `npm install fastboot-cli`)](https://github.com/heroku/heroku-buildpack-ember-cli-deploy/blob/08e7b60af704203e8cf7cb691955fc0f995edc51/buildpack/mrblib/buildpack/commands/compile.rb#L57-L64) — I'm not sure the value of `NPM_CONFIG_PRODUCTION` at this point, but I believe that the result of that npm install is some of the deps installed by yarn earlier are now removed. The Heroku output contains some lines like this:
```
remote: npm notice created a lockfile as package-lock.json. You should commit this file.
remote: + fastboot-cli@0.1.0
remote: added 8 packages, removed 1151 packages and updated 123 packages in 15.857s
```

After this, I can use `heroku run bash` to get to a shell and verify that `node_modules/rollbar` is no longer present (and my app crashes when it tries to start due to the `require('rollbar')` failing.

There are two successful workarounds I've attempted:
  - remove the yarn.lock and commit a package-json.lock
  - move all of my devDependencies into dependencies

I think that if this code were changed to use `yarn` when present, that may solve this problem:
https://github.com/heroku/heroku-buildpack-ember-cli-deploy/blob/08e7b60af704203e8cf7cb691955fc0f995edc51/buildpack/mrblib/buildpack/commands/compile.rb#L57-L64

**Comment by bantic** [comment]
I gave this another shot this morning and having `rollbar` in the `dependencies` section of `package.json` now seems to work ok. I'll close this — I am wondering if it might have been a dependency-caching issue on Heroku's side.

**Comment by bantic** [comment]
Actually — when trying this yesterday I had accidentally committed both package-lock.json and yarn.lock. Removing the package-lock.json causes this issue to reappear, so I think it is legitimate after all.

**Comment by sdhull** [comment]
This seems like a real problem. Everyone is being instructed to migrate to `yarn` and (from looking at  the linked code) it looks this buildpack is incompatible with yarn projects. Apparently it's well-known that [doing `npm install` in a yarn project corrupts node_modules](https://github.com/yarnpkg/yarn/issues/5240).

Looks like it's time to fork & fix & open a PR...

**Comment by sdhull** [comment]
@bantic did you figure this out or end up committing a `package-lock.json` to resolve it?

**Comment by bantic** [comment]
@sdhull We weren't able to come up with a workaround and we switched to using a `package-lock.json` and installing with npm only.

**Comment by sdhull** [comment]
So @bantic I asked around and found that that with the introduction of fastboot-app-server, the new recommendation is to deploy a super slim fastboot server (which has no dependencies on ember!) that you configure to download your compiled app and serve it (from s3).

Here's a blog post describing it: https://www.effective-ember.com/blog/deploying-fastboot-apps-with-ember-cli-deploy

The author told me his fastboot app server repo has a `package.json` that literally looks like this:
```js
{
name: "fastboot-server",
version: "0.0.0",
dependencies: {
fastboot-app-server: "^1.1.0",
fastboot-s3-downloader: "^0.2.1",
fastboot-s3-notifier: "^0.1.2"
},
engines: {
node: "8.9.4"
}
}
```

This way all you need is the regular node.js buildpack (which would be auto-detected I think).

**Comment by bantic** [comment]
@sdhull Thanks for responding. So the suggested solution is to skip using this buildpack entirely?

**Comment by sdhull** [comment]
@bantic correct. AFAICT, if you want to serve your ember app with fastboot, the suggested solution is to deploy a generic fastboot server that doesn't "know" anything about your app specifically. Then you set some config vars to tell it where to find your compiled app and point your DNS to it and 💥 it will download your app & serve it.

One benefit is slug size goes way, way down.

And for those who don't care about fastboot, I think deploying to S3 + Cloudfront is dead simple (with the disclaimer that there is some annoying AWS permissions config but it takes like 5 mins or less). I'd keep static file hosting off heroku.

**Comment by sdhull** [comment]
@bantic I didn't realize my colleague made our fastboot server app public. If you're interested in checking it out (and for anyone stumbling on this via google or issues search)

https://github.com/boundless-inc/ember-heroku-fastboot-app

**Comment by e-monson** [comment]
> So @bantic I asked around and found that that with the introduction of fastboot-app-server, the new recommendation is to deploy a super slim fastboot server (which has no dependencies on ember!) that you configure to download your compiled app and serve it (from s3).
> 
> Here's a blog post describing it: https://www.effective-ember.com/blog/deploying-fastboot-apps-with-ember-cli-deploy
> 
> The author told me his fastboot app server repo has a `package.json` that literally looks like this:
> 
> ```js
> {
> name: "fastboot-server",
> version: "0.0.0",
> dependencies: {
> fastboot-app-server: "^1.1.0",
> fastboot-s3-downloader: "^0.2.1",
> fastboot-s3-notifier: "^0.1.2"
> },
> engines: {
> node: "8.9.4"
> }
> }
> ```
> 
> This way all you need is the regular node.js buildpack (which would be auto-detected I think).

Is this still the recommended process as of now?



> @bantic I didn't realize my colleague made our fastboot server app public. If you're interested in checking it out (and for anyone stumbling on this via google or issues search)
> 
> https://github.com/boundless-inc/ember-heroku-fastboot-app

This doesn't seem to be public any more.

**Comment by sdhull** [comment]
@e-monson apologies, that repo is indeed no longer public.

I _believe_ that using FastbootAppServer in the way described in the linked [blog post](https://www.effective-ember.com/blog/deploying-fastboot-apps-with-ember-cli-deploy) is still the recommended approach. FWIW, the boundless `ember-heroku-fastboot-app` repo was basically identical to the `server.js` shown in that same post.

**Comment by joshwlewis** [comment]
This buildpack has been deprecated and won't be seeing any features or bugfixes. You are welcome to fork and implement it yourself if this is something you still need.
