### ISSUE TITLE
Doesn't support ember in-repo-addons

### ISSUE THREAD

**Issue by sdhull** [heroku/heroku-buildpack-ember-cli-deploy#13]
ember-cli's [in-repo-addons](https://ember-cli.com/extending/#in-repo-addons) are a useful way to isolate or extract code, especially in a monolith repo.

To properly support in-repo-addons, this buildpack would need to parse the `package.json` file, look for the `ember-addon.paths` key, and for each path, would need to cd into that path and `yarn install` (or `npm install` if there's a package-lock.json).

**Comment by joshwlewis** [comment]
This buildpack has been deprecated and won't be seeing any new features. You are welcome to fork and implement the feature yourself if this is something you still need.
