### ISSUE TITLE
Fatal error - not a git repository when using ember-cli-deploy-revision-data

### ISSUE THREAD

**Issue by jordpo** [heroku/heroku-buildpack-ember-cli-deploy#9]
When using the plugin, we get a fatal error during the ember-cli-deploy build.

**Comment by hone** [comment]
@jordpo when the buildpack gets to touch the source tree, the `.git` directories are removed, so it's not a git repo at that point.

**Comment by jordpo** [comment]
Yeah that makes sense. My specific use case I was able to use the `SOURCE_VERSION` env variable instead. I'm using a deploy plugin to upload sourcemaps to Bugsnag and I wanted to include a unique identifier for the app version. I authored the plugin so it was easy for me to adjust but I could potentially see similar issues using other sourcemap uploading plugins in the build process. Not sure there is anything that can be done on this end though. I'm fine closing this. Thank you!

**Comment by hone** [comment]
@jordpo gotcha. Maybe there should just be a heroku specific `ember-cli-deploy-revision-data` that uses `SOURCE_VERSION`?

**Comment by jordpo** [comment]
@hone I could see a Heroku flavored plugin for the revision data. I can take a stab at it.

**Comment by hone** [comment]
@jordpo sounds great. I'm going to close this then. Let me know if I can help!

When this is out, potentially we can detect for this error message and point to that addon.

**Comment by vladucu** [comment]
@jordpo also interested in this...did you had any chance to look into this?
